# Generated by Django 4.2 on 2023-04-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interface", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="engineered_prompt",
        ),
        migrations.RemoveField(
            model_name="message",
            name="gpt_reply",
        ),
        migrations.RemoveField(
            model_name="message",
            name="raw_prompt",
        ),
        migrations.AddField(
            model_name="message",
            name="message",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
