# Generated by Django 4.2 on 2023-04-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interface", "0002_remove_message_engineered_prompt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, default="2023-04-19 22:22"),
            preserve_default=False,
        ),
    ]
