# Generated by Django 4.2 on 2023-04-19 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interface", "0006_fact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fact",
        ),
    ]
