# Generated by Django 4.2 on 2023-04-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="description",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
