# Generated by Django 4.2 on 2023-04-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0002_character_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="description",
        ),
        migrations.AlterField(
            model_name="character",
            name="relationships",
            field=models.ManyToManyField(
                null=True,
                related_name="related_to",
                through="game.Relationship",
                to="game.character",
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="traits",
            field=models.ManyToManyField(null=True, to="game.trait"),
        ),
    ]
