# Generated by Django 4.2 on 2023-04-19 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0003_remove_character_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                to="game.location",
            ),
        ),
    ]
