# Generated by Django 4.2 on 2023-04-19 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0004_character_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="traits",
        ),
        migrations.AddField(
            model_name="trait",
            name="character",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="traits",
                to="game.character",
            ),
        ),
    ]
