# Generated by Django 4.2 on 2023-04-19 17:59

from django.db import migrations, models
import django.db.models.deletion
import game.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0005_remove_character_traits_trait_character"),
    ]

    operations = [
        migrations.AddField(
            model_name="relationship",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fact", models.CharField(max_length=200)),
                ("category", models.CharField(default="general", max_length=32)),
                ("keywords", models.CharField(max_length=255)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="game.character",
                    ),
                ),
            ],
            bases=(game.mixins.KeywordMixin, models.Model),
        ),
    ]
