# Generated by Django 4.2 on 2023-04-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0006_relationship_description_fact"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="end",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start",
            field=models.DateTimeField(auto_now_add=True, default="2023-04-19 22:30"),
            preserve_default=False,
        ),
    ]
